# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62aad9fcf4b1005c21be5a378b5a7398aa3160950bde302336ba4d7ad37190f619759162aca80e86894b32888b2cc0e3ab04395a7d99a019253b73be2e170b7

test:
  secret_key_base: 6f7f6ef178fb8c04098190401ae997e8d80a267eeab4cfb32604b98af1031a569f0d734c85085fccbaffb0d2271560f155666bd63bb8a7f93e5f2af45ab9ffc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
